name: Deploy to EC2

on:
  workflow_run:
    workflows: ['Docker Image CI']
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EC2_IP: ${{ secrets.EC2_HOST }}
    steps:
      - name: Setup SSH Key and Scan EC2 Host
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.EC2_IP }} >> ~/.ssh/known_hosts
      - name: Execute Deployment Commands on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ env.EC2_IP }} "
          docker pull hwangjungseok/nestjs-bapull:latest;
          docker stop nestjs-bapull || true;
          docker rm nestjs-bapull || true;
          IMAGE_ID=$(docker images -q hwangjungseok/nestjs-bapull:latest | head -n 1);
          if [ ! -z \"$IMAGE_ID\" ]; then
            docker images -q | grep -v $IMAGE_ID | xargs -r docker rmi;
          fi;
          docker run -d -p 3000:3000 --env-file /path/to/.env --restart always --name nestjs-bapull hwangjungseok/nestjs-bapull:latest"
      # - name: Verify Nginx Configuration
      #   run: |
      #     ssh -i ~/.ssh/id_rsa ubuntu@${{ env.EC2_IP }} "
      #     sudo nginx -t && sudo systemctl reload nginx"